# Generated by Django 4.1.4 on 2022-12-13 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webtask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='registered user'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_priority',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
