# Generated by Django 4.1.4 on 2022-12-14 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtask', '0006_alter_step_machine_id_alter_step_personnel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
