# Generated by Django 4.1.4 on 2022-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtask', '0007_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
    ]
