# Generated by Django 4.1.4 on 2022-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'administrator'), ('manager', 'manager'), ('without_delete', 'without_delete'), ('staff', 'staff'), ('read_only', 'read_only')], default='staff', max_length=25),
        ),
    ]
